name: CKP
favicon: null
layout_spectrum: 0.93856
typography_spectrum: 0.70742
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#272d5d'
    - '#7671ab'
    - '#c59ba9'
    - '#050505'
    - '#d36540'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
