name: CKP
favicon: null
layout_spectrum: 1
typography_spectrum: 0.77676
title: Wedding Photography and More
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b5dcfb'
    - '#006184'
    - '#2ea0d2'
    - '#67b5dc'
    - '#002039'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
