name: CKP
favicon: null
layout_spectrum: 0.6244340401608497
typography_spectrum: 0.41545654181391
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7542198938317597
  lightness: 0.5463043069466949
  saturation: 0.9093469902873039
  rhythmicContrast: 0.41121818916872144
purpose: []
